# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc17869a3b485281d2dea2f091665f3b52d0d70bf9bee615db64528cd8e25e37025187203d453abc20d3a977f1d39116770dff4bd2da0f9ba87c438b86cfc1ba

test:
  secret_key_base: af03a1640b7c9a61b582296600c1ce444e2a08f63bbd74debec55beffabc029e77366afb56c423cc2a84dc697238d7539a55ddd7909494f750130c13b50cb48b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
